### ISSUE TITLE
Wrap JavaScript Inside UMD

### ISSUE THREAD

**Issue by dozymoe** [tovic/color-picker#1]
Wrap the javascript with [UMD](https://github.com/umdjs/umd) for users who wanted to use bundler.

**Comment by tovic** [comment]
Will add this soon in duplicate file named as `color-pocker.umd.js` or maybe you could just create a fork of my project and add the UMD support so that I can link your modified version to the README file :+1:

**Comment by tovic** [comment]
Sorry I decided to not add this support by default. But [this repository](https://github.com/fidian/fid-umd) may be useful for you. [Online demo](https://rawgit.com/fidian/fid-umd/master/www/demo.html) using the _rawgit_ service.
