### ISSUE TITLE
Question: How to turn off the function fit()

### ISSUE THREAD

**Issue by chang-zhao** [tovic/color-picker#13]
Greetings, Taufik!
Sorry that the question is about my poor knowledge of Javascript, rather than about your plugin.
I make Color Picker draggable, see [http://geekpic.net/pm-2V8CLM.html](http://geekpic.net/pm-2V8CLM.html)
On screen resize it appears at the beginning of the screen though, see [http://geekpic.net/pm-I27H4B.html](http://geekpic.net/pm-I27H4B.html)
That's because function fit() doesn't understand it changes position.
How can I turn off that function?
I understand I can edit the js file or set a hook, but can I just write in my scripts something like
`CP.fit = function () {};` or `window.CP.fit = function () {};`?
I tried these but that doesn't work.
Thank you.

By the way, I can add my variation to your examples of usage of `color-picker` - draggable and with customizable palette.

**Comment by tovic** [comment]
Overwrite the `fit` method on the instance variable?

~~~ .javascript
picker.fit = function() {
    // do nothing ...
};
~~~

**Comment by chang-zhao** [comment]
No idea why, but this doesnt work...

```
    picker = new CP(document.getElementById('color-pik'), false);

    picker.fit = function () {
        alert("OK");        // do nothing
    };
```
These are inside `window.onload = function() {`, but that doesn't matter, right?

**Comment by tovic** [comment]
The last commit fix the issue.
