### ISSUE TITLE
Close Color Picker on Blur

### ISSUE THREAD

**Issue by Elias-Black** [tovic/color-picker#16]
Hi!

If we init CP with 'onfocus' event, the CP doesn't closing when input is unfocusing.

Thank you for your job!

**Comment by tovic** [comment]
Currently not possible to be implemented because when you start to drag the sliders, at the same time you will also trigger the blur (unfocus) event which will immediately hide the color picker pane.

**Comment by tovic** [comment]
~~~ .js
var target = document.querySelector('#target');

var picker = new CP(target, false);

picker.on("change", function(color) {
	this.target.value = '#' + color;
});

target.onfocus = function() {
	picker.enter();
};

target.onblur = function() {
	picker.exit();
};
~~~

https://jsfiddle.net/tovic/dfosmkkj
