### ISSUE TITLE
Question for what happend when i clicked on "ok"

### ISSUE THREAD

**Issue by STFNJNG** [tovic/color-picker#19]
Hey, nice plugin, thanks for that.
i got a question:
is it possible to call a js-function when clicking on "ok" (after i choose a color)?

thanks for everyone who get's interested and taking time to help.

Stefan

**Comment by tovic** [comment]
I am on mobile now. The original plugin does not have any _Okay_ button. Are you refer to [this](https://tovic.github.io/color-picker/color-picker.state.html) example?

**Comment by STFNJNG** [comment]
Hi tovic, thank you for your reply. After the color is picked i can click on the "okay / check" button.
On click, the textbox gets the hex-code value of the picked up color.

so my question is, how to call a function in my script instead of changing the value of the text-box?

can you send me the source-code of your example or make a fiddle out of it? thanks for your time and work.
kind regards, Stefan

**Comment by tovic** [comment]
I will give you the example when I am on desktop.

**Comment by tovic** [comment]
![2017-05-11_105655](https://cloud.githubusercontent.com/assets/1669261/25931779/99bbb17e-3638-11e7-898e-a9fea4e675aa.png)

~~~ .js
var target = document.querySelector('input'),
    picker = new CP(target),
    color = document.createElement('div'),
    button = document.createElement('a');

color.className = 'color-picker--color';

button.className = 'color-picker--button';
button.innerHTML = 'OK';
button.onclick = function() {
  target.value = color.title;
  picker.exit();
  return false;
};

picker.on("change", function(v) {
  color.title = '#' + v;
  color.style.backgroundColor = '#' + v;
});

picker.on("enter", function() {
  this.picker.appendChild(color);
  this.picker.appendChild(button);
});
~~~

https://jsfiddle.net/hnbe8sm5/4
