### ISSUE TITLE
Broken when Trying to Use with Tachyons.io

### ISSUE THREAD

**Issue by kepi** [tovic/color-picker#2]
After adding tachyons framework stylesheets, color picker breaks.

To reproduce simply add tachyons css to header (i.e. in `color-picker.noob.html`)

`<link rel="stylesheet" href="https://npmcdn.com/tachyons@4.0.4/css/tachyons.css">`

Looks like there is some incompatibility with tachyons resets or something similar. Problem is probably with `.color-picker-sv`

**Comment by tovic** [comment]
~~~ .css
.color-picker,
.color-picker * {
  -webkit-box-sizing:padding-box;
  -moz-box-sizing:padding-box;
  box-sizing:padding-box;
}
~~~

**Comment by kepi** [comment]
Thansk for fast reply. I have to use `content-box` instead of `padding-box` as Chrome claims it doesn't know `padding-box` property. Working like a charm now.

```css
.color-picker,
.color-picker * {
  box-sizing: content-box;
}

```

**Comment by tovic** [comment]
I will set a `border-box` value to all of the color picker panel elements next time.
