### ISSUE TITLE
Issue with Emitter

### ISSUE THREAD

**Issue by LeCoupa** [tovic/color-picker#20]
When I install `color-picker` with npm, the following error occurs when I try to import the package:

```bash
Module build failed: Error: ENOENT: no such file or directory, open '.../node_modules/emitter/dist/emit
```

When I install the package with `npm install --save emitter`, the error seems to disappear in the terminal but a new one occurs in Chrome:

```javascript
Uncaught (in promise) TypeError: Emitter is not a function
```

If you inspect the file `index.js` in `node_modules`, this seems to come from:

```javascript
/**
 * Mixin Emitter.
 */

Emitter(ColorPicker.prototype);
```

For the first issue, I suggest you add this package as a module dependency in `package.json`. For the second one, I don't have any answer.

**Comment by tovic** [comment]
The module name is simply `CP`, not `ColorPicker`. Are there some automation on replacing _slug-case_ into _PascalCase_ behind the proccess?

**Comment by LeCoupa** [comment]
I understand now... How can I install color-picker with NPM? Did you register the package? Because you named it color-picker in package.json but there is already a package registered with that name.

https://www.npmjs.com/package/color-picker

So when I run `npm install --save color-picker`, it does not install your package.

**Comment by tovic** [comment]
I didn&rsquo;t use package manager by myself, so my experience with it is very poor. I created the `package.json` file based on another JavaScript project. It should have been registered but unfortunately it doesn&rsquo;t.

**Comment by LeCoupa** [comment]
Are you going to register it? Do you need help?

**Comment by tovic** [comment]
I&rsquo;d love to. But for the next 3 months probably I will be out from my computer for a while. I don&rsquo;t want to make everybody waiting so I will try to learn it by myself if I have a spare time. Thanks.

**Comment by tovic** [comment]
https://www.npmjs.com/package/c-p
