### ISSUE TITLE
Initialize instance with predefined color

### ISSUE THREAD

**Issue by gregBerthelot** [tovic/color-picker#22]
Hi

How can I initialize the color picker instance with the one set in target element https://jsfiddle.net/Greggg/916wwx1h/

Any help would be appreciated

**Comment by tovic** [comment]
Use `data-color` attribute:

``` .js
pickers.forEach(function(picker) {
  let color = window.getComputedStyle(picker).getPropertyValue('background-color');
  picker.setAttribute('data-color', color);
  new CP(picker);
});
```

https://jsfiddle.net/916wwx1h/22/

**Comment by gregBerthelot** [comment]
Thanks a lot @tovic. 

Can I ask some more help? On https://jsfiddle.net/Greggg/0dxwa9wr/ I am adding a background-image to `.color-view` to simulate grid background transparency and the background-color disappear. Just remove the background-image to `.color-view` in css part to see what I mean.

Thanks again

**Comment by gregBerthelot** [comment]
Another thing, I am looking for a way to set position of picker bottom-left instead of bottom-right of target :)

**Comment by tovic** [comment]
Use the `fit` hook to re-set the color picker pane position:

``` .js
var picker = new CP(document.querySelector('input'));

picker.on("fit", function() {
  var width = this.picker.offsetWidth,
      left = this.target.offsetLeft;
  this.picker.style.left = (left + this.target.offsetWidth - width) + 'px';
});
```

https://jsfiddle.net/4mj8hcjd/

**Comment by gregBerthelot** [comment]
Got it. Thanks for your help and for the lib ;-)

**Comment by gregBerthelot** [comment]
Got it but is there a way to append the picker to a DOM element to fix the issue with scrolling here https://jsfiddle.net/Greggg/6g4bLkg6/ 

We can reposition it programmatically but…

**Comment by tovic** [comment]
Could you move this case to a new issue with title something like: _append picker to a specific DOM_ or _picker scrolling bug_?

Thanks.

**Comment by tovic** [comment]
See #23
