### ISSUE TITLE
Is there a way to attach the picker to a certain container rather than <body> ??

### ISSUE THREAD

**Issue by meeshh** [tovic/color-picker#23]
i am facing an issue that my picker is attached to body while i have the trigger in a container inside with overflow. the picker gets its x and y positions on initialization and position itself according to body but not the container that i need. so once i scroll down, the picker looks like it's fixed but it is actually absolute.
![screen shot 2017-11-16 at 3 42 28 pm](https://user-images.githubusercontent.com/620224/32894616-f2b1dbfe-cae5-11e7-8a5c-1209b02bbb9b.png)

**Comment by tovic** [comment]
Currently not possible to set custom offset based on the parent container, but you can set custom pane container [this way](https://github.com/tovic/color-picker/blob/7397a74e72b8b8f18444ce5c550e286b7eb063db/color-picker.static.html#L42):

~~~ .js
picker.on("fit", function() {
    this.enter(document.querySelector('aside'));
});
~~~

For now, you can update the color picker pane offset during scroll event this way:

~~~ .js
aside.addEventListener("scroll", function() {
    if (picker.visible) {
        picker.picker.style.top = the_top_value;
        picker.picker.style.left = the_left_value;
    }
}, false);
~~~

**Comment by tovic** [comment]
Currently not possible to set custom offset based on the parent container, but you can set custom pane container [this way](https://github.com/tovic/color-picker/blob/7397a74e72b8b8f18444ce5c550e286b7eb063db/color-picker.static.html#L42):

~~~ .js
picker.on("fit", function() {
    this.enter(document.querySelector('aside'));
});
~~~

For now, you can update the color picker pane offset during scroll event this way:

~~~ .js
aside.addEventListener("scroll", function() {
    if (picker.visible) {
        picker.picker.style.top = the_top_value;
        picker.picker.style.left = the_left_value;
    }
}, false);
~~~

**Comment by tovic** [comment]
See this quick fix &rarr; https://tovic.github.io/color-picker/color-picker.scroll.html
