### ISSUE TITLE
Bug of Relative/Absolute/Fixed Container(s) Position

### ISSUE THREAD

**Issue by tovic** [tovic/color-picker#29]
![test](https://user-images.githubusercontent.com/1669261/35732828-862921e0-084d-11e8-8dac-6921f91e655f.gif)

**Comment by alex3683** [comment]
Hi,
I had the same issue when using the picker within a scrollable modal dialog. In your code you calculate the position within the picker relatively complicated using scroll offsets and document coordinates. You could simplify this (and avoid positioning issues) when only using viewport relative positions and then ignore all scrolling.
I fixed it by changing the `point` function as follows:
```js
        // get mouse/finger coordinate
        function point(el, e) {
            var x = !!e.touches ? e.touches[0].clientX : e.clientX,
                y = !!e.touches ? e.touches[0].clientY : e.clientY,
                o = el.getBoundingClientRect();
            return {
                x: x - o.left,
                y: y - o.top
            };
        }
```
I tested it in Internet Explorer 11, Firefox 58 and Chrome 63.
Hope it helps 😃

**Comment by alex3683** [comment]
Hi,
just wanted to ask, if and when you plan to adopt this change. If you want I can try to provide a Pull Request.

**Comment by tovic** [comment]
Sure, just do it.

**Comment by tovic** [comment]
https://github.com/tovic/color-picker/commit/85fd4bfdcb899de272b6080bbd79f99bd138d5dd

**Comment by alex3683** [comment]
Thanks for fixing it. I can confirm that the bug is fixed now. And sorry I didn't provide the pull request I proposed ...

**Comment by tovic** [comment]
Somehow, this fix breaks the touch event support?

**Comment by tovic** [comment]
https://stackoverflow.com/a/34972180

**Comment by tovic** [comment]
Fixed here https://github.com/tovic/color-picker/issues/32
