### ISSUE TITLE
Best Approach to Always Visible Color Picker?

### ISSUE THREAD

**Issue by kepi** [tovic/color-picker#3]
In my use case I want to always display color picker. Have it displayed on start and leave it displayed even when color is selected or I click to different place on page.

As for showing on start I suppose that `cp.enter()` is enough but I'm not sure what is best approach to remove exit (click?) event. I tried simply to `cp.off('exit')` destroy etc but no luck.

Thanks for help

**Comment by tovic** [comment]
[Here](https://github.com/tovic/color-picker/blob/264a8a3905bbc0842065f3625e12ceb88e1e5afd/color-picker.color-rgba.html#L44&L48) you will see that I force the color picker to keep visible on HTML5 range input mouse-up/touch-end with a timer like this:

~~~ .javascript
function keep() {
    window.setTimeout(function() {
        picker.enter(); // re-enter on exit
    }, .01);
}

picker.on("exit", keep);
~~~

**Comment by kepi** [comment]
Thanks. It is probably good enough as workaround in some situations. In my case it casues blinking/flickering when redrawing so I end up with simply removing on("exit"... from source code :)

Anyway, it is completely ok. I think that my use case isn't in line with targets of your color-picker so I don't think it need some special treatement.

**Comment by tovic** [comment]
Yeah, because I just think that the native HTML5 color input also does not have fixed-always-visible color picker.

**Comment by tovic** [comment]
https://rawgit.com/tovic/color-picker/master/color-picker.static.html
