### ISSUE TITLE
npm version outdated

### ISSUE THREAD

**Issue by alex3683** [tovic/color-picker#34]
Would be great, if you could release the current version on npm too. I'm currently referencing a specific tag in my package.json (which is not that great ;-))

**Comment by evolross** [comment]
+1  GitHub says you're on 1.4 but npm says 1.3.10.  Is 1.4 not official yet?

**Comment by tovic** [comment]
How? I have updated them recently.

**Comment by tovic** [comment]
Ah, okay I forgot. So, I have to do `npm version v1.4.0` and do `npm publish` instead of just `npm update`

https://docs.npmjs.com/getting-started/publishing-npm-packages
