### ISSUE TITLE
copy paste not working

### ISSUE THREAD

**Issue by putrasurya** [tovic/color-picker#35]
also, if i trigger change event manually of input with jquery also not working

**Comment by tovic** [comment]
Do you have an example? The event listener system in this plugin doesn&rsquo;t have any relation to the native `node.addEventListener`.

**Comment by tovic** [comment]
To enable paste events in the color input, you need to do that [manually](https://tovic.github.io/color-picker/color-picker.value-update.html).

**Comment by putrasurya** [comment]
it's working! thanks! 
i think the process is too complicated, it will be good if the copy paste can be the default setting of this plugin

**Comment by tovic** [comment]
Use the [instance iterator](https://tovic.github.io/color-picker#section:extend):

~~~ .js
CP.each(function($) {
    function update() {
        $.set(this.value).enter();
    }
    $.target.oncut = update;
    $.target.onpaste = update;
    $.target.onkeyup = update;
    $.target.oninput = update;
});
~~~

Or, just wrap your modifications to a new function:

~~~ .js
var runCP = function(node, events, bounds) {
    var $ = new CP(node, events, bounds);
    function update() {
        $.set(this.value).enter();
    }
    $.target.oncut = update;
    $.target.onpaste = update;
    $.target.onkeyup = update;
    $.target.oninput = update;
    return $;
};
~~~

Then:

~~~ .js
var picker = runCP(document.querySelector('input'));

picker.on("change", function() { … });
~~~
