### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [tovic/color-picker#39]
Hi bro @tovic .. What do you think about this logo? if you like it, i'll sent to you. 

![cp](https://user-images.githubusercontent.com/36124339/46578966-6ddad180-ca33-11e8-96b1-778bf33281f9.png)

Best Regard. :)

**Comment by tovic** [comment]
At the moment, I am more likely to like the logo design which consists of one to three colors without any gradient and special effects at all. I want to make them look uniform on all projects. Just take this as _my style_.

![42131860](https://user-images.githubusercontent.com/1669261/46582464-7651fd00-ca71-11e8-9820-d65bceeb8aaa.png)

![7410731](https://user-images.githubusercontent.com/1669261/46582463-75b96680-ca71-11e8-97b4-190963531c7e.png)

**Comment by mirzazulfan** [comment]
Hi @tovic ,, i've designed 2 version. is there anything you want? if you need something else, i'll fix it. Thanks
![cp](https://user-images.githubusercontent.com/36124339/46658286-92be7880-cbdc-11e8-95f5-8ec427d93e29.png)

**Comment by mirzazulfan** [comment]
Hi @tovic . What about this ?
![cp v 2](https://user-images.githubusercontent.com/36124339/47600397-a5adb700-d9ea-11e8-9130-065831d3b60e.png)

**Comment by tovic** [comment]
I would probably take the shape but not the color. I will update the comment here when I have decided the proper color, thanks.

**Comment by mirzazulfan** [comment]
Thank you. Im wait for it. :) Good luck for the project.

**Comment by tovic** [comment]
I&rsquo;ll take the logo but probably will remove the bevel/rounded effect. I will also change the color but don&rsquo;t worry I will credit you as the contributor.

**Comment by mirzazulfan** [comment]
Im glad to hear that, if you need anything please let me know. Thanks you. Good luck with your project. Best regard.
