### ISSUE TITLE
Gak bisa di Enter / Paste-Code Hex nya

### ISSUE THREAD

**Issue by kangrian** [tovic/color-picker#4]
Tolong di perbaiki, terima kasih kang tovic. ^_^

**Comment by tovic** [comment]
Contoh kasusnya bagaimana mas?

**Comment by kangrian** [comment]
ketika saya coba paste kode hex yang saya gak tau warna apa itu ke field input. background nya gak berubah sesuai kode hex yg saya paste. saya kira bisa berubah sesuai kode yg saya paste ketika di enter. hhee

**Comment by kangrian** [comment]
thx udh d respond sblmnya mas.

**Comment by tovic** [comment]
~~~ .javascript
var picker = new CP(document.querySelector('input'));

picker.on("drag", function(color) {
    this.target.value = '#' + color;
});

function update() {
    picker.set(this.value);
}

picker.target.onkeyup = update;
picker.target.oncut = update;
picker.target.onpaste = update;
picker.target.oninput = update;
~~~

**Comment by tovic** [comment]
https://github.com/tovic/color-picker/issues/15
