### ISSUE TITLE
Calling enter() doesn't fire enter hook.

### ISSUE THREAD

**Issue by evolross** [tovic/color-picker#42]
Because of my issues with `visibility` not updating, I'm having to manually manage my own visibility flag using the `enter` and `exit` hooks.  This works pretty good except if I open the color picker manually with another button using:
```
CP.__instance__.someColorPicker.enter()
```
The `enter` hook doesn't get fired.  This would be expected behavior no?  As then I could put all my flag management code in one place - the `enter` and `exit` hooks versus having to add code wherever I call `enter()`.

Strangely, calling the above with `exit()` does indeed fire the `exit` hook.

This can be reproduced easily by putting a `console.log` in the `picker.on('enter') {}`, create a new color picker instance, then in Chrome's console call `CP.__instance__.someColorPicker.enter()`.  It won't fire the `enter` hook.  However, it will fire if you manually click the color picker to enter it.

**Comment by tovic** [comment]
I am afraid it will produce nested function call if I put the `enter` hook trigger inside the method itself, but I will try to fix it soon.

**Comment by evolross** [comment]
All your hooks seem to run "after" the event though... not really like an override, correct?  The `enter` event simply fires after `enter()` is called.  Same with `fit`, etc.

I thought these `on` events were simply ways to do stuff _after_ those actual functions occurred.

**Comment by tovic** [comment]
_SIGH!_ It turns out that it&rsquo;s because we lost the `enter` hook from the start. I can&rsquo;t find it with **CTRL+F**.

A small change [here](https://github.com/tovic/color-picker/blob/7fe4ecc909cddbd7bcc6f43fefd1c4f43dbb685e/color-picker.js#L592-L594) should fix the issue:

~~~ .js
$.enter = function(bucket) {
    return create(0, bucket), trigger("enter", [$]), $;
};
~~~

**Comment by evolross** [comment]
Hmm... if the `enter` hook is missing altogether, why does the `enter` event fire correctly upon clicking the color picker text field?  That still works.

**Comment by evolross** [comment]
There's one issue possibly here... now when the `enter` event gets fired and I have the code:
```
picker.on("enter", function(picker) {
   console.log("picker.on enter was fired...", picker);
   ...
});
```
There is no `picker` or `event` passed into the listener. It returns undefined.  

When you have the same type of listener for the `fit` event, you get the picker passed.
```
picker.on("fit", function(picker) {
   console.log("picker.on fit was fired...", picker);
   ...
});
```
And the `picker` is the picker object.  So you do things like `picker.self.offsetLeft`, etc.

**Comment by tovic** [comment]
Now they are removed. You could simply use `this`:

~~~ .js
picker.on("fit", function() {
   console.log(["picker.on fit was fired...", this]);
});
~~~
