### ISSUE TITLE
Keep Color Picker Open On Mouseup Outside Container

### ISSUE THREAD

**Issue by jjrabbit** [tovic/color-picker#47]
When holding down the mouse button on a color and dragging the cursor outside the color-picker container then releasing the mouse results in the color picker closing.

Is it possible to only close the color picker on 'click' outside of container instead of on 'mouseup'?

**Comment by tovic** [comment]
Try this:

~~~ .js
picker.on("change", function() {
    // ...
    // ...
    this.enter(); // Show!
});
~~~

**Comment by jjrabbit** [comment]
Ok will use enter() method. Thanks tovic!
