### ISSUE TITLE
Using multiple color pickers on a single page.

### ISSUE THREAD

**Issue by anankitpatil** [tovic/color-picker#52]
I'm using multiple color pickers om my page. On opening one opens the picker on the others too. Is there any way to avoid this?

**Comment by tovic** [comment]
Have you ever look at this example page?

https://tovic.github.io/color-picker/color-picker.picker.html

The basic would be something like this:

~~~ .js
function applyColorPickersTo(selector) {
    document.querySelectorAll(selector).forEach($ => {
        new CP($);
    });
}

applyColorPickersTo('#container input');
