### ISSUE TITLE
Change Color on Click

### ISSUE THREAD

**Issue by kepi** [tovic/color-picker#6]
I noticed in all your examples, that color is changed with `on('drag')` but it doesn't work when you click only (both in -sv and -h).

I tried to play with different events but only one which worked was `on('stop')`. Problem with that one is that it is interfering with input field. I'm not able i.e. to click in middle of input field because cursor is immediately moved to the end.

I think changing color with click should be possible by default.

**Comment by tovic** [comment]
Use `change` event.

**Comment by kepi** [comment]
Thanks, works like a charm.
