### ISSUE TITLE
Impossible To Click Into Middle of Input in Chrome

### ISSUE THREAD

**Issue by kepi** [tovic/color-picker#8]
In Chrome I'm not able to position cursor in input field with mouse click. Trying on: https://rawgit.com/tovic/color-picker/master/color-picker.static.html but it is same on all examples.

Every time I click into input field, cursor is moved to the end of field. Moving with arrows on keyboard works without any problem.

In Firefox it works without any problem.

**Comment by tovic** [comment]
Untested but it may be caused by the default method to trigger the color picker visibility using click event instead of focus. Will try to fix this next time.

**Comment by tovic** [comment]
Removed the `event.stopPropagation()` part and replace it with a timer. For static color picker hack example, combine `start` and `drag` event to mimic the `change` event. This should be unified into a `change` event in the future if possible.

**Comment by kepi** [comment]
Thanks, works fine for me this way.

**Comment by tovic** [comment]
Is now possible to be unified to `change`. See the source code of the updated `color-picker.static.html` file.
